// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ProjectEuler")>]
[<assembly: AssemblyProductAttribute("ProjectEuler")>]
[<assembly: AssemblyDescriptionAttribute("A Project Euler solution in F#")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ProjectEuler"
    let [<Literal>] AssemblyProduct = "ProjectEuler"
    let [<Literal>] AssemblyDescription = "A Project Euler solution in F#"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
